# .github/workflows/ci.yml

name: Django CI

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # These services are like a mini-docker-compose for the CI job
    services:
      postgres:
        image: postgres:14-alpine
        # Provide the same environment variables as your docker-compose file
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        # Health check to wait until postgres is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      # We need to provide the environment variables for Django to connect to the DB
      env:
        SECRET_KEY: 'a-dummy-secret-key-for-testing-purposes'
        DEBUG: 'True'
        DB_NAME: test_db
        DB_USER: test_user
        DB_PASSWORD: test_password
        DB_HOST: localhost # In GitHub Actions, the service is available on localhost
        DB_PORT: 5432 # The default port for the postgres service
      run: |
        python manage.py test

